### ISSUE TITLE
Static volume snapshot binding failure

### ISSUE THREAD

**Issue by liyinan926** [kubernetes-csi/external-snapshotter#198]
I was playing with static volume snapshot binding by first creating a `VolumeSnapshotContent` object and then a `VolumeSnapshot` object that is supposed to be bound to the `VolumeSnapshotContent` object by the external-snapshotter. However, I'm getting the following error:

```
Failed to check and update snapshot: failed to get input parameters to create snapshot <volume-snapshot-name>: "the snapshot source is not specified."
``` 

The `VolumeSnapshot` was created with the `source` field unspecified because the intention is to statically bind it to the `VolumeSnapshotContent` object. My understanding is that the `source` field is optional in this scenario, according to the comment of the field copied and pasted below.

```
// If not specified, user can create VolumeSnapshotContent and bind it with VolumeSnapshot manually.
```

The `VolumeSnapshot` object looks like the following:

```
apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: mongo-persistent-storage-mongo-0-vs
  namespace: default
spec:
  snapshotClassName: default-snapshot-class
  snapshotContentName: snapcontent-31dffc80-073a-11ea-830c-42010a800239
```

I'm using the version `v1.1.0` of `external-snapshotter`.

@xing-yang @jingxu97 @yuxiangqian
