### ISSUE TITLE
`VolumeSnapshotContentStatus` field type inconsistency

### ISSUE THREAD

**Issue by astraw99** [kubernetes-csi/external-snapshotter#595]
When get a ready `VolumeSnapshotContentStatus`: `kubectl get volumesnapshotcontent snapcontent-xxx -oyaml`
got follows output:
```
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotContent
metadata:
  ...
spec:
  ...
status:
  creationTime: 1633315996000000000
  readyToUse: true
  restoreSize: 536870912000
  snapshotHandle: snap-xxx
```

To be consistent with `VolumeSnapshotStatus`:
the `creationTime: 1633315996000000000` should be like `creationTime: "2021-10-04T02:53:16Z"`
the `restoreSize: 536870912000` should be like `restoreSize: 500Gi`
