### ISSUE TITLE
Break out snapshot CRD libraries into separate repo

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/external-snapshotter#60]
This makes it easier to update external-provisioner dependencies

**Comment by xing-yang** [comment]
This is a good idea.  I'll work on this after the v1.13 release.

**Comment by msau42** [comment]
cc @nikhita is this something that the k8s publishing bot can help with?

**Comment by nikhita** [comment]
> cc @nikhita is this something that the k8s publishing bot can help with?

Yes :)

From our conversation on Slack: iiuc this repo is supposed to be canonical source of truth and the  `client` (and maybe the `api`) directory needs to be published/synced to another repo.

For this, we'll just need a set of rules like https://github.com/kubernetes/kubernetes/blob/master/staging/publishing/rules.yaml. Very roughly, it'll look something like:

```
rules:
- destination: published-client-repo-name
  library: true
  branches:
  - source:
      branch: master
      dir: pkg/client
    name: master
    dependencies:
    - repository: api
      branch: master
    - repository: apimachinery
      branch: master
    - repository: client-go
      branch: master
```

We'll also need a cluster to run this bot. Maybe wg-k8s-infra can help with this? cc @dims 

/cc @sttts
