### ISSUE TITLE
Snapshot webhook doesn't throw error if volumesnapshotclass is not provided

### ISSUE THREAD

**Issue by GunaKKIBM** [kubernetes-csi/external-snapshotter#771]
**What happened**:
I created snapshot providing the following input. 
```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: snapshot-0
spec:
  source:
    persistentVolumeClaimName: pvc1
```
But when I created snapshot providing, empty string as shown below, I see the expected error
```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: snapshot-1
spec:
  volumeSnapshotClassName: "" 
  source:
    persistentVolumeClaimName: pvc1
```
Error:
```
% kubectl create -f volumeSnapshot.yaml 
Error from server: error when creating "volumeSnapshot.yaml": admission webhook "validation-webhook.snapshot.storage.k8s.io" denied the request: Spec.VolumeSnapshotClassName must not be the empty string
```

**What you expected to happen**:
I expected to see the same error as mentioned above even when I don't provide the volumeSnapshotClassName

**How to reproduce it**:
Create a snapshot with the following yaml provided that a pvc exists
```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: snapshot-0
spec:
  source:
    persistentVolumeClaimName: pvc1
```

**Environment**:
- Driver version: External snapshotter version - v6.0.1
- Kubernetes version (use `kubectl version`): 1.24
- OS (e.g. from /etc/os-release): Ubuntu 18.04.6 LTS
- Kernel (e.g. `uname -a`): 4.15.0-189-generic
- Install tools: Deployed using https://github.com/kubernetes-csi/external-snapshotter/tree/v6.0.1/deploy/kubernetes/webhook-example this READme
