### ISSUE TITLE
Provide more metadata in CreateSnapshot request

### ISSUE THREAD

**Issue by aschi1** [kubernetes-csi/external-snapshotter#774]
**Is your feature request related to a problem?/Why is this needed**
We are backing up our PVC's in Kubernetes via snapshots which are then stored in AWS console. Since the metadata provided in a `CreateSnapshot` request does not contain pvc name, pvc namespace or pv name we cant really distinguish between them in AWS console. We would like to be able to know what PVC does a snapshot belong to when looking in AWS console snapshots. This is only compounded when you have multiple snapshots being created every hour

**Describe the solution you'd like in detail**
Provide metadata PVC name, PVC namespace and PV name in `CreateSnapshot` request to CSI driver. At this moment only a small set of metadata is [exposed](https://github.com/kubernetes-csi/external-snapshotter/blob/7c1ca796b13bdd7606a22978b762242888145cbc/pkg/sidecar-controller/snapshot_controller.go#L314-L318).

**Describe alternatives you've considered**
We tried tagging more stuff in Velero. We added more tags to CSI driver which are then passed to the volumes it creates. We added tag specification to `StorageClass`. Volumes are tagged. But no matter what we do the snapshots still do not contain these tags.

**Additional context**
At first we thought we need to request this change on CSI driver (currently using AWS EBS CSI driver since we are running on EKS). I found an [existing issue](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1261) where this was discussed. They added functionality which enables us to add tags to `VolumeSnapshotClass`. After asking about dynamic tags based on PVC name etc we were forwarded to the external snapshotter project since they are not receiving any metadata in the `CreateSnapshot` request.

**Example of `VolumeSnapshotClass` we wanted to use**
```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: delete-vsc
  labels:
    velero.io/csi-volumesnapshot-class: "true"
driver: ebs.csi.aws.com
deletionPolicy: Delete
parameters:
  tagSpecification_1: "pvc_namespace={{ .PVCNamespace }}"
  tagSpecification_2: "pvc_name={{ .PVCName }}"
  tagSpecification_3: "pv_name={{ .PVName }}"
```

If any additional information is required I will be happy to try to provide it. Thank you for considering this enhancement
