### ISSUE TITLE
name of the snapshot not showing in aws

### ISSUE THREAD

**Issue by gabrielpvbw** [kubernetes-csi/external-snapshotter#789]
The name of the snapshot is not showing in aws. I am not sure if it's suppose to be like that, but I would like to have the actual snapshot name in aws as well.

Right now it only has a dash there

![image](https://user-images.githubusercontent.com/100797215/202535109-505fa795-616e-43db-aeea-3a8e37c56355.png)

**Comment by xing-yang** [comment]
What name are you expecting to show up there?  The name of the VolumeSnapshot?

What is your observation of the volume?  Does it behave differently?

**Comment by gabrielpvbw** [comment]
Hi, thanks for your help. I want to somehow identify the snapshot in aws by name tag. Could be the name of the VolumeSnapshot or a custom name of my choice. But I don't know if that's possible.

**Comment by xing-yang** [comment]
There is a way to set extra-create-metadata flag to true when csi-snapshotter is started. If true, the VolumeSnapshot's name / namespace and the VolumeSnapshotContent's name will be passed as parameters to the CSI driver in CreateSnapshotRequest. I don't know if AWS EBS CSI driver uses this flag though.  You may want to check with AWS EBS driver maintainers.
https://github.com/kubernetes-csi/external-snapshotter/blob/v6.1.0/cmd/csi-snapshotter/main.go#L71

**Comment by gabrielpvbw** [comment]
Ok, but where in my yaml files I can set this ?

**Comment by marcusschiesser** [comment]
@gabrielpvbw @xing-yang you can configure `extra-create-metadata=true` in the `setup-snapshotcontroller.yaml`, e.g.:

```yaml
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: snapshot-controller
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: snapshot-controller
  minReadySeconds: 15
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: snapshot-controller
    spec:
      serviceAccountName: snapshot-controller
      containers:
        - name: snapshot-controller
          image: registry.k8s.io/sig-storage/snapshot-controller:v6.1.0
          args:
            - "--v=5"
            - "--leader-election=true"
            - "--extra-create-metadata=true"
          imagePullPolicy: IfNotPresent
```

Unfortunately, aws-csi-driver (chart version: 2.16.0, app version 1.15.0) is not picking up the information and the AWS console still shows `-` as name.
