### ISSUE TITLE
Waiting for a snapshot stucks

### ISSUE THREAD

**Issue by danilo-lopes** [kubernetes-csi/external-snapshotter#807]
**What happened**:

Tried to create PVC snapshot and it stucks in "Waiting for a snapshot <Volume Snapshot reference> to be created by the CSI driver"

**What you expected to happen**:

Volume snapshot return "ReadyToUse" = true

**How to reproduce it**:
```
git clone https://github.com/kubernetes-csi/external-snapshotter.git

cd external-snapshotter

kubectl kustomize client/config/crd | kubectl create -f -
kubectl -n kube-system kustomize deploy/kubernetes/snapshot-controller | kubectl create -f -

cat << EOF | kubectl apply -f -
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
allowVolumeExpansion: false
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2
  fsType: ext4
EOF

cat << EOF | kubectl apply -f -
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-vol-gp2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
EOF

cat << EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: foo-pod
  name: foo-pod
  namespace: default
spec:
  containers:
  - image: busybox
    name: foo-pod
    resources: {}
    volumeMounts:
    - name: data-vol-gp2
      mountPath: /data
    command:
    - '/bin/sh'
    - '-c'
    - 'while true; do now=$(date +%d-%m-%y+%H:%M:%S); echo "Now is $now"; echo "file processed - $now" > /data/file-$(echo $now); sleep 20; now=""; done'
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: data-vol-gp2
    persistentVolumeClaim:
      claimName: data-vol-gp2
EOF

cat << EOF | kubectl apply -f -
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: ebs-csi-aws
driver: ebs.csi.aws.com
deletionPolicy: Delete
EOF

cat << EOF | kubectl apply -f -
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: data-vol-gp2-snapshot
  namespace: default
spec:
  volumeSnapshotClassName: ebs-csi-aws
  source:
    persistentVolumeClaimName: data-vol-gp2
EOF
```

```
k get vsclass
NAME          DRIVER            DELETIONPOLICY   AGE
ebs-csi-aws   ebs.csi.aws.com   Delete           19m

k get vs
NAME                    READYTOUSE   SOURCEPVC      SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS   SNAPSHOTCONTENT                                    CREATIONTIME   AGE
data-vol-gp2-snapshot   false        data-vol-gp2                                         ebs-csi-aws     snapcontent-df6e08d4-2448-4f79-aee6-3d6423a4cf26                  19m

k describe vs |grep Events -A 3
Events:
  Type    Reason            Age   From                 Message
  ----    ------            ----  ----                 -------
  Normal  CreatingSnapshot  20m   snapshot-controller  Waiting for a snapshot default/data-vol-gp2-snapshot to be created by the CSI driver.

k get events --sort-by '.metadata.creationTimestamp'
LAST SEEN   TYPE     REASON                   OBJECT                                 MESSAGE
21m         Normal   WaitForFirstConsumer     persistentvolumeclaim/data-vol-gp2     waiting for first consumer to be created before binding
21m         Normal   ExternalProvisioning     persistentvolumeclaim/data-vol-gp2     waiting for a volume to be created, either by external provisioner "ebs.csi.aws.com" or manually created by system administrator
21m         Normal   Provisioning             persistentvolumeclaim/data-vol-gp2     External provisioner is provisioning volume for claim "default/data-vol-gp2"
21m         Normal   ProvisioningSucceeded    persistentvolumeclaim/data-vol-gp2     Successfully provisioned volume pvc-728c03fb-4b44-495b-8364-9a2e3cc3e355
21m         Normal   Scheduled                pod/foo-pod                            Successfully assigned default/foo-pod to ip-172-16-1-117.us-east-2.compute.internal
21m         Normal   SuccessfulAttachVolume   pod/foo-pod                            AttachVolume.Attach succeeded for volume "pvc-728c03fb-4b44-495b-8364-9a2e3cc3e355"
21m         Normal   Pulling                  pod/foo-pod                            Pulling image "busybox"
21m         Normal   Pulled                   pod/foo-pod                            Successfully pulled image "busybox" in 191.140823ms
21m         Normal   Created                  pod/foo-pod                            Created container foo-pod
21m         Normal   Started                  pod/foo-pod                            Started container foo-pod
20m         Normal   CreatingSnapshot         volumesnapshot/data-vol-gp2-snapshot   Waiting for a snapshot default/data-vol-gp2-snapshot to be created by the CSI driver.
```

**Anything else we need to know?**:
CSI EBS Driver Installation:

```
helm upgrade --install aws-ebs-csi-driver aws-ebs-csi-driver/aws-ebs-csi-driver --values values.yaml -n kube-system
```
```
helm list -n kube-system |grep csi
NAME                        	NAMESPACE  	REVISION	UPDATED                             	STATUS  	CHART                             	APP VERSION
aws-ebs-csi-driver          	kube-system	1       	2022-12-20 07:13:00.112428 -0300 -03	deployed	aws-ebs-csi-driver-2.13.0         	1.13.0
```

values.yaml:
```
controller:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::<IAM Account>:role/gondor-csi-ebs-controller-irsa
    create: true
    name: ebs-csi-controller-sa
```

**Environment**:
- Driver version: latest
- Kubernetes version (use `kubectl version`): v1.24.7-eks-fb459a0
- OS (e.g. from /etc/os-release): amazon linux 2
- Install tools: kustomize

**Logs**:

[ebs-csi-controller_csi_provisioner.log](https://github.com/kubernetes-csi/external-snapshotter/files/10425791/ebs-csi-controller_csi_provisioner.log)
[snapshot-controller-leader.log](https://github.com/kubernetes-csi/external-snapshotter/files/10425792/snapshot-controller-leader.log)

**Comment by danilo-lopes** [comment]
Missing the snapshotter sidecar on ebs csi driver..

values.yaml:

```
...
sidecars:
  snapshotter:
    # Enables the snapshotter sidecar even if the snapshot CRDs are not installed
    forceEnable: true
```
