### ISSUE TITLE
Define the VolumeSnapshotContent name from VolumeSnapshot object

### ISSUE THREAD

**Issue by ebuildy** [kubernetes-csi/external-snapshotter#847]
**Is your feature request related to a problem?/Why is this needed**

When creating a dynamic VolumeSnapshot from a PVC, the snapshotName is coming from VolumeSnapshot UID:

```
snapshotName, err := makeSnapshotName(handler.snapshotNamePrefix, string(content.Spec.VolumeSnapshotRef.UID), handler.snapshotNameUUIDLength)
```

(from https://github.com/kubernetes-csi/external-snapshotter/blob/master/pkg/sidecar-controller/csi_handler.go#L73)

Hence this is not a relevant name but a UID.

As such, provider like Azure will create a disk with this UID, not linked to the initial VolumeSnapshot object.

**Describe the solution you'd like in detail**

A new field or an annotation to override this behavior:

``` 
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: new-snapshot-test
  annotations:
    csi.storage.k8s.io/volumesnapshotcontent/name: new-snapshot-test
spec:
  volumeSnapshotClassName: csi-hostpath-snapclass
  source:
    persistentVolumeClaimName: pvc-test
```

**Describe alternatives you've considered**

Get the generated UID, remove all VolumeSnapshot object, rename disk via azure CLI

**Additional context**

https://github.com/kubernetes-csi/external-snapshotter/blob/master/pkg/sidecar-controller/csi_handler.go#L73
