### ISSUE TITLE
VolumeGroupSnapshots - how to rebuild/restore a VolumeGroupSnapshot?

### ISSUE THREAD

**Issue by tesshuflower** [kubernetes-csi/external-snapshotter#969]
**What happened**:

When creating a VolumeGroupSnapshot from multiple PVCs, it's a bit unclear how to do a restore.

It looks like you are required to individually restore each volumesnapshot in the group into a PVC - but is there an easy way to map each volumesnapshot back to the original PVC it was taken from?

The volumegroupsnapshot has status that lists `volumesnapshots` but doesn't provide information (as far as I can tell) linking them back to the original PVC.

Example `volumegroupsnapshot` status:

```
status:
  boundVolumeGroupSnapshotContentName: groupsnapcontent-84656059-5c4b-4289-9d8f-464f4085b331
  creationTime: "2023-11-30T18:43:03Z"
  readyToUse: true
  volumeSnapshotRefList:
  - kind: VolumeSnapshots
    name: snapshot-6e37158c2ce07fe27cba4ef0bc84c58f2801d344bdffff539aa1b786ab57d1e4-2023-11-30-6.43.3
    namespace: source
    uid: 6d0e0c03-696a-4f0b-a136-3a2c026f360e
  - kind: VolumeSnapshots
    name: snapshot-d01f061e29fb3f492579b031b9bcd6723e7ad4860c647e4397a89aea375ff116-2023-11-30-6.43.4
    namespace: source
    uid: c1ae59ad-8a36-4630-90c8-b45d4b9d42e2
```

There is some information about the PVs in the volumegroupsnapshotcontent object, but again I'm not sure how to map this to the individual snapshots.

**What you expected to happen**:

In order to restore a volumegroupsnapshot I need to be able to restore each snapshot to the proper PVC.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
